version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: pes-carpool-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=pes_carpool

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pes-carpool-backend
    restart: always
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=pes_carpool
      - JWT_SECRET=pes-carpool-secret-key-change-in-production
      - CORS_ORIGINS=*
      - CO2_EMISSION_GRAMS_PER_KM=120
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pes-carpool-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8001
    depends_on:
      - backend

volumes:
  mongodb_data: